#encoding UTF-8
<div class="entry-content blog-outer" itemprop="text">
    <br>
    <img style="display: block; margin-left: auto; margin-right: auto;" src="/images/oeffingen.png" alt="" />
    <br>
    <h2 data-sourcepos="1:1-1:23">Datenschutzerkl&auml;rung</h2>
    <p data-sourcepos="3:1-3:41"><strong>Keine Datenerhebung und keine Cookies</strong></p>
    <p data-sourcepos="5:1-5:79">Diese Website erhebt keine personenbezogenen Daten und verwendet keine Cookies.</p>
    <p data-sourcepos="7:1-7:17"><strong>Zugriffsdaten</strong></p>
    <p data-sourcepos="9:1-9:179">Der Webserver dieser Website speichert standardm&auml;&szlig;ig in seinen Logfiles Informationen, die Ihr Browser bei jedem Zugriff auf die Website &uuml;bermittelt. Diese Informationen umfassen:</p>
    <ul data-sourcepos="11:1-16:0">
    <li data-sourcepos="11:1-11:32">Datum und Uhrzeit des Zugriffs</li>
    <li data-sourcepos="12:1-12:29">URL der abgerufenen Website</li>
    <li data-sourcepos="13:1-13:72">Referrer-URL (die Website, von der Sie auf diese Website gelangt sind)</li>
    <li data-sourcepos="14:1-14:40">Verwendeter Browser und Betriebssystem</li>
    <li data-sourcepos="15:1-16:0">IP-Adresse des anfragenden Rechners</li>
    </ul>
    <p data-sourcepos="17:1-17:159">Diese Daten werden ausschlie&szlig;lich zur statistischen Auswertung und zur Verbesserung der Website verwendet. Eine personenbezogene Auswertung findet nicht statt.</p>
    <p data-sourcepos="19:1-19:16"><strong>Einwilligung</strong></p>
    <p data-sourcepos="21:1-21:125">Mit der Nutzung dieser Website erkl&auml;ren Sie sich mit der Speicherung und Verarbeitung der oben genannten Daten einverstanden.</p>
    <p data-sourcepos="23:1-23:11"><strong>Kontakt</strong></p>
    <p data-sourcepos="25:1-25:120">Wenn Sie Fragen zum Datenschutz auf dieser Website haben, k&ouml;nnen Sie sich jederzeit an den <a href="../impressum">Betreiber</a> der Website wenden.</p>
    <p data-sourcepos="27:1-27:173"><strong>Hinweis:</strong> Bitte beachten Sie, dass diese Datenschutzerkl&auml;rung jederzeit ge&auml;ndert werden kann. Die aktuelle Version der Datenschutzerkl&auml;rung finden Sie auf dieser Website.</p>
    <p data-sourcepos="27:1-27:173">&nbsp;</p>
</div>