#encoding UTF-8
<div class="entry-content about-outer" itemprop="text">
    <br>
    <img style="display: block; margin-left: auto; margin-right: auto;" src="/images/oeffingen.png" alt="" />
    <br>
    <h1 style="text-align: center;">Impressum</h1>
    <p style="text-align: center;">&nbsp;</p>
    <h2 style="text-align: center;">Angaben gem&auml;&szlig; &sect; 5 TMG</h2>
    <p style="text-align: center;"><strong>Name:</strong> Thomas Straub</p>
    <p style="text-align: center;"><strong>E-Mail:</strong> <a href="mailto:info@wetter-oeffingen.de">info@wetter-oeffingen.de</a></p>
    <p style="text-align: center;">&nbsp;</p>
    <h2 style="text-align: center;">Verantwortlich f&uuml;r den Inhalt</h2>
    <p style="text-align: center;"><strong>Name des Verantwortlichen:</strong> Thomas Straub</p>
    <p style="text-align: center;">&nbsp;</p>
    <h2 style="text-align: center;">Haftungsausschluss</h2>
    <p style="text-align: center;">Trotz sorgf&auml;ltiger Kontrolle &uuml;bernehmen ich keine Haftung f&uuml;r die Inhalte externer Links. <br />F&uuml;r den Inhalt der verlinkten Seiten sind ausschlie&szlig;lich deren Betreiber verantwortlich.</p>
    <p style="text-align: center;">&nbsp;</p>
    <h2 style="text-align: center;">Urheberrecht</h2>
    <p style="text-align: center;">Die Inhalte dieser Website sind urheberrechtlich gesch&uuml;tzt. <br />Die Vervielf&auml;ltigung, Verbreitung oder sonstige Nutzung ohne schriftliche <br />Zustimmung des Urhebers ist untersagt.</p>
    <h2 style="text-align: center;">&nbsp;</h2>
    <h2 style="text-align: center;">Kontakt</h2>
    <p style="text-align: center;">Sie k&ouml;nnen mich per E-Mail an <a href="mailto:info@wetter-oeffingen.de"><br />info@wetter-oeffingen.de</a> <br />kontaktieren.</p>
    <p style="text-align: center;">&nbsp;</p>
    <p style="text-align: center;">&nbsp;</p>   
</div>