#encoding UTF-8
<div class="entry-content ordner-outer" itemprop="text">
	<p>&nbsp;</p>
<h1 style="text-align: center;">Homepage Update-Historie</h1>
<div style="margin-left: 20px;">
<h2 style="text-align: center;">&nbsp;</h2>
<h2 style="text-align: center;"><strong>2024</strong></h2>
<h3 style="text-align: center;">7. April - Domains</h3>
<p style="text-align: center;"><strong>Neue Domains:</strong> Die Wetterseite ist nun auch unter den Domains <a href="https://OeffWetter.de">OeffWetter.de</a> und <a href="https://Oeffingen-Wetter.de">Oeffingen-Wetter.de</a> erreichbar, um die Zug&auml;nglichkeit und Auffindbarkeit zu verbessern.</p>
<hr />
<h3 style="text-align: center;">2. April - Dienst&uuml;berwachung</h3>
<p style="text-align: center;"><strong>Dienst&uuml;berwachung hinzugef&uuml;gt:</strong> Eine Dienst&uuml;berwachung wurde implementiert, um den Dienst "weewx" automatisch neu zu starten, falls der GW1100 kurzzeitig offline geht und der Dienst abst&uuml;rzt.</p>
<hr />
<h3 style="text-align: center;">14. Februar - WeeWX 5.0 Update</h3>
<p style="text-align: center;"><strong>Update auf WeeWX 5.0:</strong> Die Wetterstation wurde auf die neueste Version von WeeWX (Version 5.0) aktualisiert, um von den neuesten Funktionen und Verbesserungen zu profitieren.</p>
<hr />
<h3 style="text-align: center;">5. Februar - Kiosk</h3>
<p style="text-align: center;"><strong>Kiosk-Seite &Uuml;berarbeitung:</strong> Die Kiosk-Seite wurde f&uuml;r eine optimale Darstellung auf Tablets &uuml;berarbeitet, um die Benutzerfreundlichkeit zu erh&ouml;hen.</p>
<hr />
<h2 style="text-align: center;">&nbsp;</h2>
<h2 style="text-align: center;"><strong>2023</strong></h2>
<h3 style="text-align: center;">20. Dezember - Serverwechsel</h3>
<p style="text-align: center;"><strong>Serverwechsel:</strong> Umstellung auf einen ARM Server von Netcup, der bis jetzt eine sehr stabile Leistung zeigt und die Zuverl&auml;ssigkeit der Webseite erh&ouml;ht.</p>
<hr />
<h3 style="text-align: center;">19. August - Blitzsensor</h3>
<p style="text-align: center;"><strong>Blitzsensor-Installation:</strong> Ein Ecowitt Blitzsensor wurde installiert, um die Wetterdatenerfassung um wichtige Informationen zu Gewitteraktivit&auml;ten zu erweitern.</p>
<hr />
<h3 style="text-align: center;">25. April - Hardware</h3>
<p style="text-align: center;"><strong>Hardware-Upgrade:</strong> Ein neues Ecowitt GW1100 Empfangsmodul wurde in Betrieb genommen, das eine Echtzeitverbindung erm&ouml;glicht und die Daten&uuml;bertragung verbessert.</p>
<hr />
<h3 style="text-align: center;">21. April - Server-Upgrade</h3>
<p style="text-align: center;"><strong>Server-Upgrade:</strong> Der VPS von Netcup wurde aufgrund h&auml;ufiger &Uuml;berlastungen durch einen leistungsst&auml;rkeren Server ersetzt, um Ausfallzeiten zu minimieren.</p>
<hr />
<h3 style="text-align: center;">21. April - Skin-R&uuml;ckwechsel</h3>
<p style="text-align: center;"><strong>Skin-R&uuml;ckwechsel:</strong> R&uuml;ckkehr zum Belchertown Skin, um eine bessere Vorhersagefunktionalit&auml;t zu bieten.</p>
<hr />
<h2 style="text-align: center;">&nbsp;</h2>
<h2 style="text-align: center;"><strong>2022</strong></h2>
<h3 style="text-align: center;">10. November - Servercrash</h3>
<p style="text-align: center;"><strong>Servercrash:</strong> Nach einem Update kam es zu einem Servercrash, der eine kurze Offline-Zeit zur Folge hatte. Die Probleme wurden jedoch schnell behoben.</p>
<hr />
<h3 style="text-align: center;">8. Oktober - Skin-Wechsel</h3>
<p style="text-align: center;"><strong>Skin-Wechsel:</strong> Wechsel zum WDC Skin, um das Design der Webseite zu modernisieren und die Benutzererfahrung zu verbessern.</p>
<hr />
<h3 style="text-align: center;">3. Oktober - Pers&ouml;nliches Ereignis</h3>
<p style="text-align: center;"><strong>Pers&ouml;nliches Ereignis:</strong> Ein kleiner pers&ouml;nlicher Meilenstein &ndash; der Geburtstag des Webseitenbetreibers.</p>
<hr />
<h3 style="text-align: center;">22. Juli - Serverumzug</h3>
<p style="text-align: center;"><strong>Serverumzug:</strong> Wechsel von einem lokalen Server auf einen Onlinehoster (Netcup), um eine h&ouml;here Verf&uuml;gbarkeit und bessere Performance zu erreichen.</p>
<hr />
<h2 style="text-align: center;">&nbsp;</h2>
<h2 style="text-align: center;">2021</h2>
<h3 style="text-align: center;">26. November - Sturmschaden</h3>
<p style="text-align: center;"><strong>Sturmschaden:</strong> Die Wetterstation erlitt leichte Besch&auml;digungen durch einen Sturm, was jedoch keine Auswirkungen auf die Daten&uuml;bertragung hatte.</p>
<hr />
<h3 style="text-align: center;">5. September - Webseite-Launch</h3>
<p style="text-align: center;"><strong>Webseite-Launch:</strong> Die Webseite <a href="https://Wetter-Oeffingen.de">Wetter-Oeffingen.de</a> ging live und begann mit der Bereitstellung von Wetterdaten f&uuml;r die &Ouml;ffentlichkeit.</p>
<hr />
<h3 style="text-align: center;">2. September - Domain-Registrierung</h3>
<p style="text-align: center;"><strong>Domain-Registrierung:</strong> Die Domain <a href="https://Wetter-oeffingen.de">Wetter-oeffingen.de</a> wurde registriert, um die Online-Pr&auml;senz der Wetterstation zu etablieren.</p>
<hr />
<h3 style="text-align: center;">6. August - Aufzeichnungsbeginn</h3>
<p style="text-align: center;"><strong>Aufzeichnungsbeginn:</strong> Start der Wetterdatenaufzeichnung lokal auf einem Raspberry Pi 4, der den Grundstein f&uuml;r das Projekt legte.</p>
<hr /></div>
</div>