#encoding UTF-8
<div class="entry-content about-outer" itemprop="text">
    <br>
  <img style="display: block; margin-left: auto; margin-right: auto;" src="/images/oeffingen.png" alt="" />
  <h2 data-sourcepos="3:1-3:54">&nbsp;</h2>
  <h1 data-sourcepos="3:1-3:54"><strong>Infoseite meiner Wetterstation!</strong></h1>
  <p data-sourcepos="5:1-5:101">Hier finden Sie alle wichtigen Informationen rund um meine Wetterstation, die folgende Daten sammelt:</p>
  <ul data-sourcepos="7:1-14:0">
  <li data-sourcepos="7:1-7:16"><strong>Temperatur</strong></li>
  <li data-sourcepos="8:1-8:22"><strong>Luftfeuchtigkeit</strong></li>
  <li data-sourcepos="9:1-9:25"><strong>Windgeschwindigkeit</strong></li>
  <li data-sourcepos="10:1-10:18"><strong>Windrichtung</strong></li>
  <li data-sourcepos="11:1-11:18"><strong>Niederschlag</strong></li>
  <li data-sourcepos="12:1-12:18"><strong>UV-Strahlung</strong></li>
  <li data-sourcepos="13:1-14:0"><strong>Solarstrahlung<br /><br /></strong></li>
  </ul>
  <p data-sourcepos="15:1-15:159">Empfangen werden die Daten mit dem Ecowitt GW1100 Empfangsmodul.</p>
  <p data-sourcepos="15:1-15:159">Die Daten werden in Echtzeit per 868MHz an den Ecowitt-client (GW1100) gesendet und von da per WLan an den vServer zur WeeWx software geschickt.</p>
  <p data-sourcepos="17:1-17:70">Die Wetterstation befindet sich auf 281 Meter &uuml;ber Meeresspiegel.</p>
  <p data-sourcepos="19:1-19:106">Zus&auml;tzlich wurde ein Ecowitt Blitzsensor eingebunden, um Gewitter in der Umgebung fr&uuml;hzeitig zu erkennen.</p>
  <p data-sourcepos="21:1-21:121">F&uuml;r die Zukunft ist die Installation einer Wettercam geplant, um die Wetterbedingungen auch visuell zu dokumentieren.</p>
  <p data-sourcepos="23:1-23:102">F&uuml;r die Darstellung der Daten verwende ich WeeWx in der Version 5 mit dem Skin Belchertown / WDC.</p>
  <h2 data-sourcepos="25:1-25:21"><strong><br />Technische Daten:</strong></h2>
  <ul data-sourcepos="27:1-33:0">
  <li data-sourcepos="27:1-27:53"><strong>Modell der Wetterstation:</strong>&nbsp;Froggit WH3000 SE PRO</li>
  <li data-sourcepos="28:1-28:43"><strong>Hersteller der Wetterstation:</strong>&nbsp;Froggit</li>
  <li data-sourcepos="29:1-29:128"><strong>Messparameter:</strong>&nbsp;Temperatur, Luftfeuchtigkeit, Windgeschwindigkeit, Windrichtung, Niederschlag, UV-Strahlung, Solarstrahlung</li>
  <li data-sourcepos="30:1-30:174"><strong>Genauigkeit der Messungen:</strong>&nbsp;&plusmn;0,5 &deg;C (Temperatur), &plusmn;2 % (Luftfeuchtigkeit), &plusmn;2 m/s (Windgeschwindigkeit), &plusmn;3 &deg; (Windrichtung), &plusmn;10 % (UV-Strahlung), &plusmn;5 % (Solarstrahlung)</li>
  <li data-sourcepos="31:1-31:38"><strong>Funkreichweite:</strong>&nbsp;100 m (freifeld)</li>
  <li data-sourcepos="32:1-33:0"><strong>Stromversorgung:</strong>&nbsp;Netzteil (optional Solarbetrieb m&ouml;glich)</li>
  </ul>
  <h2 data-sourcepos="34:1-34:13"><strong>Standort:</strong></h2>
  <ul data-sourcepos="36:1-39:0">
  <li data-sourcepos="36:1-36:35"><strong>Bundesland:</strong>&nbsp;Baden-W&uuml;rttemberg</li>
  <li data-sourcepos="37:1-37:40"><strong>H&ouml;he &uuml;ber dem Meeresspiegel:</strong>&nbsp;281 m</li>
  <li data-sourcepos="38:1-39:0"><strong>Umgebungsbedingungen:</strong>&nbsp;Freiland</li>
  </ul>
  <h2 data-sourcepos="40:1-40:19"><strong>Datenerfassung:</strong></h2>
  <ul data-sourcepos="42:1-45:0">
  <li data-sourcepos="42:1-42:35"><strong>Aktualisierungsrate:</strong>&nbsp;1 Minute</li>
  <li data-sourcepos="43:1-43:150"><strong>Gespeicherte Daten:</strong>&nbsp;Temperatur, Luftfeuchtigkeit, Windgeschwindigkeit, Windrichtung, Niederschlag, UV-Strahlung, Solarstrahlung, Blitzeinschl&auml;ge</li>
  <li data-sourcepos="44:1-45:0"><strong>Zugriff auf die Daten:</strong>&nbsp;Webbrowser, Smartphone-App</li>
  </ul>
  <h2 data-sourcepos="46:1-46:25"><strong>Auswertung der Daten:</strong></h2>
  <ul data-sourcepos="48:1-51:0">
  <li data-sourcepos="48:1-48:133"><strong>Beobachtbare Wetterph&auml;nomene:</strong>&nbsp;Temperatur&auml;nderungen, Luftfeuchtigkeitsschwankungen, Windrichtungswechsel, Niederschlag, Gewitter</li>
  <li data-sourcepos="49:1-49:75"><strong>Nutzung der Daten:</strong>&nbsp;Wettervorhersage, Gartenpflege, Freizeitgestaltung</li>
  <li data-sourcepos="50:1-51:0"><strong>Tipps und Tricks:</strong>&nbsp;Regelm&auml;&szlig;ige Wartung der Wetterstation, Datenanalyse mit WeeWx</li>
  </ul>
  <h2 data-sourcepos="58:1-58:12"><strong>Website:</strong></h2>
  <ul data-sourcepos="60:1-62:0">
  <li data-sourcepos="60:1-60:59">Diese Website wird auf einem vServer von Netcup gehostet.</li>
  </ul>
  <h2 data-sourcepos="58:1-58:25"><strong><br />Fragen und Antworten:</strong></h2>
  <h3 data-sourcepos="60:1-60:55"><strong>Welche Software nutzt du zur Darstellung der Daten?</strong></h3>
  <p data-sourcepos="62:1-62:67">Ich verwende WeeWx in der Version $station.version mit dem Skin Belchertown $belchertown_version / WDC.<br /><br /></p>
  <h3 data-sourcepos="64:1-64:55"><strong>Wie kann ich die Daten deiner Wetterstation nutzen?</strong></h3>
  <p data-sourcepos="66:1-66:182">Die Daten meiner Wetterstation sind frei zug&auml;nglich und k&ouml;nnen f&uuml;r verschiedene Zwecke verwendet werden, z. B. f&uuml;r die Wettervorhersage, die Gartenpflege oder die Freizeitgestaltung.<br /><br /></p>
  <h3 data-sourcepos="68:1-68:63"><strong>Wo finde ich weitere Informationen zu deiner Wetterstation?</strong></h3>
  <p data-sourcepos="70:1-70:148">Weitere Informationen zu meiner Wetterstation finden Sie auf dieser Website. Sie k&ouml;nnen mir auch gerne eine E-Mail schreiben, wenn Sie Fragen haben.</p>
  <h2 data-sourcepos="72:1-72:101"><strong><br />Statistiken:</strong></h2>
  <ul>
  <li>Station hardware: $station.hardware</li>
  <li>Server uptime: $station.os_uptime.long_form</li>
  <li>WeeWX uptime: $station.uptime.long_form</li>
  <li>WeeWX version: $station.version</li>
  <li>Belchertown Skin Version: $belchertown_version</li>
  </ul>
  <p data-sourcepos="72:1-72:101">&nbsp;</p>
  <p data-sourcepos="72:1-72:101"><strong>Ich hoffe, dass diese Infoseite Ihnen n&uuml;tzliche Informationen rund um meine Wetterstation bietet.</strong></p>
  <p data-sourcepos="74:1-74:49"><strong>Viel Spa&szlig; beim Erkunden meiner Wetterstation!</strong></p>
